apiVersion: v1
kind: Pod
metadata:
  name: env-todo-api
  labels:
    app: todoapi
spec:
  containers:
    - name: todo-api
      image: localhost:5000/argonaultes-it-works:4.0
      env:
        - name: API_TOKEN
          valueFrom:
            configMapKeyRef:
              name: todosconfigmap
              key: OTHER_TOKEN
        - name: API_TOKEN_2
          valueFrom:
            configMapKeyRef:
              name: todoapiconfig2
              key: SUPER_TOKEN
        - name: API_TOKEN_3
          valueFrom:
            secretKeyRef:
              name: todoapisecret
              key: apitoken
