apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"savenginx","creationTimestamp":null,"labels":{"app":"savenginx"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"savenginx"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"savenginx"}},"spec":{"containers":[{"name":"nginx","image":"nginx:latest","resources":{}}]}},"strategy":{}},"status":{}}
  creationTimestamp: "2025-07-09T08:10:27Z"
  generation: 1
  labels:
    app: savenginx
  name: savenginx
  namespace: default
  resourceVersion: "18485"
  uid: a259164b-4929-4596-b43f-b30f7d8f61cf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: savenginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: savenginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-09T08:10:29Z"
    lastUpdateTime: "2025-07-09T08:10:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-09T08:10:27Z"
    lastUpdateTime: "2025-07-09T08:10:29Z"
    message: ReplicaSet "savenginx-7f8468f7f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
